### ISSUE TITLE
Дока

### ISSUE THREAD

**Issue by nepster-web** [russianlagman/yii2-eav#1]
Здравствуйте. Существует ли дока по данному расширению ?

**Comment by metalagman** [comment]
Доки нет, но скоро будет. Там все задокументировано достаточно подробно в коде ))

**Comment by maxlapko** [comment]
Добрый день, пожалуйста приведите пример использования данной библиотеки. (куски кода и тд)

**Comment by ghost** [comment]
Да очень нужна дока!!! ))))

**Comment by spanov** [comment]
Алексей, будьте любезны, объясните каким образом можно использовать Вашу разработку?
1) Миграция сделана
2) Behavior подключен

если выводить в форме, вот так:

``` php
<?= $form->field($model->getEav(), 'eav3'); ?>
```

Поле выводится, но оно текстовое.
При попытке вывести его через виджет, получается очень некрасиво, которое толком не работает. 

``` php
<? foreach($model->getEav()->handlers as $key=>$eav): ?>
<?= $form->field($model->getEav(), $key)->widget($eav, [
'owner' => $model->getEav(),
'activeForm' => $form            // только этот activeForm находится в DynamicModel
'attributeModel' => ... // тут тоже магия
]); ?>
<? endforeach;?>
```

**Comment by metalagman** [comment]
Переработал экстеншн, сделал доку https://github.com/yarcode/yii2-eav
